# Generated by Django 3.2.7 on 2021-09-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_comment', models.CharField(max_length=300, verbose_name='Текст комментария')),
                ('user_name', models.CharField(max_length=30, verbose_name='Ник пользователя')),
                ('name_track', models.CharField(max_length=30, verbose_name='Под каким треком')),
            ],
            options={
                'verbose_name': 'Коментарий',
                'verbose_name_plural': 'Коментарии',
            },
        ),
        migrations.CreateModel(
            name='Traks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('performer', models.CharField(max_length=20, verbose_name='Исполнитель')),
                ('album', models.CharField(max_length=20, verbose_name='Альбом')),
                ('date_relised', models.CharField(max_length=20, verbose_name='Дата выхода')),
                ('trak', models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='file')),
            ],
            options={
                'verbose_name': 'Трек',
                'verbose_name_plural': 'Треки',
            },
        ),
    ]
